#!/usr/bin/env python3
"""
Use DeepSeek-R1 to generate a comprehensive LFT test script.
This demonstrates the AI-powered topology generation capabilities.
"""

import sys
import os
from pathlib import Path

# Add project to path
sys.path.insert(0, str(Path(__file__).parent))

print("=" * 70)
print("LFT AI Test Script Generator using DeepSeek-R1")
print("=" * 70)

# Import the AI generator
print("\n[1/4] Loading DeepSeek-R1 model...")
print("      (This may take 30-60 seconds for first-time initialization)")

try:
    from profissa_lft.ai_generator import ModernAITopologyGenerator
    
    # Initialize with default (now DeepSeek-R1)
    generator = ModernAITopologyGenerator(
        use_hf_api=False,  # Use local model
        load_in_8bit=True   # Use 8-bit quantization for memory efficiency
    )
    
    print("      ✓ DeepSeek-R1 loaded successfully!")
    
    # Display model info
    model_info = generator.get_model_info()
    print(f"\n[2/4] Model Information:")
    print(f"      • Model: {model_info.get('model_name', 'Unknown')}")
    print(f"      • Type: {model_info.get('model_type', 'Unknown')}")
    print(f"      • Device: {model_info.get('device', 'Unknown')}")
    print(f"      • Parameters: {model_info.get('parameters', 0):,}")
    
    # Generate a comprehensive test topology
    print(f"\n[3/4] Generating LFT test topology...")
    
    prompt = """Create a comprehensive LFT test script that demonstrates the following:
1. Create a simple SDN topology with:
   - An SDN controller (using OpenDaylight)
   - One OpenFlow switch
   - Three hosts (h1, h2, h3)
2. Connect the controller to the switch
3. Connect all three hosts to the switch
4. Configure IP addresses for all hosts (use 10.0.0.x/24 network)
5. Set up proper interfaces
6. Add comments explaining each step
7. Include a main block that instantiates everything and prints success messages

Make it a complete, runnable Python script with proper imports from profissa_lft."""
    
    generated_code = generator.generate_topology(prompt)
    
    print("      ✓ Topology generated successfully!")
    
    # Save the generated code
    output_file = "lft_test_topology_generated.py"
    print(f"\n[4/4] Saving generated test script to '{output_file}'...")
    
    with open(output_file, 'w') as f:
        f.write("#!/usr/bin/env python3\n")
        f.write('"""\n')
        f.write("LFT Test Topology - Generated by DeepSeek-R1\n")
        f.write("This script was automatically generated using AI to demonstrate LFT capabilities.\n")
        f.write('"""\n\n')
        f.write(generated_code)
    
    # Make it executable
    os.chmod(output_file, 0o755)
    
    print(f"      ✓ Test script saved successfully!")
    
    print("\n" + "=" * 70)
    print("✅ SUCCESS! Test script generated using DeepSeek-R1")
    print("=" * 70)
    print(f"\nGenerated file: {output_file}")
    print(f"Code length: {len(generated_code)} characters")
    print("\nTo run the test:")
    print(f"  python3 {output_file}")
    print("\nTo view the code:")
    print(f"  cat {output_file}")
    print("=" * 70)
    
except Exception as e:
    print(f"\n❌ Error: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

