#!/usr/bin/env python3
"""
LFT AI - Practical Examples Collection
This file contains ready-to-use examples for common scenarios
"""

from profissa_lft import ModernAITopologyGenerator
import os
import time
from datetime import datetime


class LFTAIExamples:
    """Collection of practical LFT AI topology generation examples"""
    
    def __init__(self, output_dir="ai_generated_examples"):
        """Initialize examples generator"""
        self.output_dir = output_dir
        self.generator = None
        os.makedirs(output_dir, exist_ok=True)
    
    def init_generator(self, model="deepseek-r1"):
        """Initialize the AI generator once for all examples"""
        print("="*70)
        print("LFT AI - Practical Examples Collection")
        print("="*70)
        print(f"Initializing {model} model...")
        print("   Please wait 30-60 seconds...\n")
        
        start = time.time()
        self.generator = ModernAITopologyGenerator(
            model_name=model,
            load_in_8bit=True
        )
        elapsed = time.time() - start
        print(f"✓ Generator ready in {elapsed:.1f} seconds!\n")
    
    def _generate_and_save(self, name, description):
        """Helper to generate and save a topology"""
        print(f"\n{'='*70}")
        print(f"Example: {name}")
        print(f"{'='*70}")
        print(f"Description:\n{description.strip()}\n")
        
        start = time.time()
        
        try:
            # Generate
            code = self.generator.generate_topology(description)
            elapsed = time.time() - start
            
            # Validate
            compile(code, '<string>', 'exec')
            
            # Save
            filename = os.path.join(self.output_dir, f"{name}.py")
            with open(filename, 'w') as f:
                f.write(code)
            
            # Add header comment
            header = f"""#!/usr/bin/env python3
'''
Generated by: LFT AI (DeepSeek-R1)
Example: {name}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Description: {description.strip().splitlines()[0]}
'''

"""
            with open(filename, 'r') as f:
                original = f.read()
            with open(filename, 'w') as f:
                f.write(header + original)
            
            # Make executable
            os.chmod(filename, 0o755)
            
            print(f"✓ Generated in {elapsed:.1f}s")
            print(f"✓ Saved: {filename}")
            print(f"✓ Lines: {len(code.splitlines())}")
            print(f"✓ Ready to run: sudo python {filename}")
            
            return filename
            
        except Exception as e:
            print(f"✗ Error: {e}")
            return None
    
    def example_1_basic_sdn(self):
        """Example 1: Basic SDN Network"""
        return self._generate_and_save(
            "01_basic_sdn_network",
            """
            Create a basic Software-Defined Network with:
            
            Components:
            - 3 hosts: h1, h2, h3
            - 1 OpenFlow switch: s1
            - 1 OpenDaylight controller: c1
            
            Network Configuration:
            - h1 IP: 10.0.0.1/24 on interface eth0
            - h2 IP: 10.0.0.2/24 on interface eth0
            - h3 IP: 10.0.0.3/24 on interface eth0
            - Controller IP: 192.168.1.100
            
            Topology:
            - Connect h1, h2, h3 to switch s1
            - Connect switch s1 to controller c1
            
            Requirements:
            - Instantiate all nodes
            - Use proper LFT methods
            """
        )
    
    def example_2_simple_wireless(self):
        """Example 2: Simple 4G Wireless Network"""
        return self._generate_and_save(
            "02_simple_4g_wireless",
            """
            Create a simple 4G/LTE wireless network with:
            
            Components:
            - 2 User Equipment: ue1, ue2
            - 1 eNodeB (base station): enb1
            - 1 Evolved Packet Core: epc1
            
            Topology:
            - Connect ue1 and ue2 to eNodeB enb1
            - Connect enb1 to EPC epc1
            
            Requirements:
            - Configure EPC with default settings
            - Instantiate all components
            - Use proper LFT wireless methods
            """
        )
    
    def example_3_redundant_network(self):
        """Example 3: Redundant Network with Failover"""
        return self._generate_and_save(
            "03_redundant_network",
            """
            Create a redundant network topology with:
            
            Components:
            - 4 hosts: h1, h2, h3, h4
            - 2 switches: s1, s2 (for redundancy)
            - 1 controller: c1
            
            Network Configuration:
            - h1: 10.0.1.1/24
            - h2: 10.0.1.2/24
            - h3: 10.0.1.3/24
            - h4: 10.0.1.4/24
            - Controller: 192.168.1.100
            
            Topology (redundant paths):
            - h1 and h2 connect to s1
            - h3 and h4 connect to s2
            - s1 and s2 are interconnected
            - Both switches connect to controller c1
            
            Requirements:
            - Instantiate all nodes
            - Create redundant paths for reliability
            """
        )
    
    def example_4_hierarchical_network(self):
        """Example 4: Hierarchical Three-Tier Network"""
        return self._generate_and_save(
            "04_hierarchical_network",
            """
            Create a hierarchical three-tier network topology:
            
            Core Layer:
            - 2 core switches: core1, core2
            - 1 controller: c1 at 192.168.1.100
            
            Distribution Layer:
            - 2 distribution switches: dist1, dist2
            
            Access Layer:
            - 4 hosts: h1, h2, h3, h4
            
            Network Configuration:
            - h1: 10.0.0.1/16
            - h2: 10.0.0.2/16
            - h3: 10.0.0.3/16
            - h4: 10.0.0.4/16
            
            Topology:
            - dist1 and dist2 connect to both core1 and core2
            - h1 and h2 connect to dist1
            - h3 and h4 connect to dist2
            - All switches managed by controller c1
            
            Requirements:
            - Instantiate all nodes
            - Follow hierarchical design principles
            """
        )
    
    def example_5_datacenter_spine_leaf(self):
        """Example 5: Datacenter Spine-Leaf Architecture"""
        return self._generate_and_save(
            "05_datacenter_spine_leaf",
            """
            Create a spine-leaf datacenter topology:
            
            Spine Layer:
            - 2 spine switches: spine1, spine2
            
            Leaf Layer:
            - 3 leaf switches: leaf1, leaf2, leaf3
            
            Servers:
            - 6 servers (2 per leaf):
              * srv1, srv2 on leaf1 (IPs: 10.1.1.1/24, 10.1.1.2/24)
              * srv3, srv4 on leaf2 (IPs: 10.1.2.1/24, 10.1.2.2/24)
              * srv5, srv6 on leaf3 (IPs: 10.1.3.1/24, 10.1.3.2/24)
            
            Topology:
            - Full mesh: Each leaf connects to both spine switches
            - Each server pair connects to its designated leaf
            
            Requirements:
            - Instantiate all components
            - Use datacenter best practices
            """
        )
    
    def example_6_campus_network(self):
        """Example 6: Campus Network with VLANs"""
        return self._generate_and_save(
            "06_campus_network",
            """
            Create a campus network topology:
            
            Core:
            - 1 core switch: core1
            - 1 controller: c1 at 192.168.1.100
            
            Buildings (3 buildings):
            Building 1:
            - Switch: bldg1_sw
            - Hosts: h1 (10.10.1.1/24), h2 (10.10.1.2/24)
            
            Building 2:
            - Switch: bldg2_sw
            - Hosts: h3 (10.10.2.1/24), h4 (10.10.2.2/24)
            
            Building 3:
            - Switch: bldg3_sw
            - Hosts: h5 (10.10.3.1/24), h6 (10.10.3.2/24)
            
            Topology:
            - All building switches connect to core switch
            - Hosts connect to their building switches
            - Core switch managed by controller
            
            Requirements:
            - Instantiate all nodes
            - Simulate campus structure
            """
        )
    
    def example_7_iot_network(self):
        """Example 7: IoT Edge Computing Network"""
        return self._generate_and_save(
            "07_iot_edge_network",
            """
            Create an IoT edge computing network:
            
            Edge Gateway:
            - 1 edge switch: edge1
            - 1 controller: c1 at 192.168.1.100
            
            IoT Devices (sensors):
            - 6 IoT devices: iot1-iot6
              * iot1: 10.20.0.1/24
              * iot2: 10.20.0.2/24
              * iot3: 10.20.0.3/24
              * iot4: 10.20.0.4/24
              * iot5: 10.20.0.5/24
              * iot6: 10.20.0.6/24
            
            Edge Servers:
            - 2 edge servers: edge_srv1, edge_srv2
              * edge_srv1: 10.20.1.1/24
              * edge_srv2: 10.20.1.2/24
            
            Topology:
            - All IoT devices connect to edge switch
            - Edge servers connect to edge switch
            - Edge switch managed by controller
            
            Requirements:
            - Instantiate all components
            - Simulate edge computing scenario
            """
        )
    
    def example_8_hybrid_network(self):
        """Example 8: Hybrid Wired + Wireless Network"""
        return self._generate_and_save(
            "08_hybrid_wired_wireless",
            """
            Create a hybrid network with both wired and wireless:
            
            Wired Core:
            - 1 core switch: core_sw
            - 1 controller: c1 at 192.168.1.100
            - 2 wired hosts: wired_h1 (10.0.0.1/24), wired_h2 (10.0.0.2/24)
            
            Wireless Network:
            - 2 User Equipment: ue1, ue2
            - 1 eNodeB: enb1
            - 1 EPC: epc1
            
            Topology:
            - Wired hosts connect to core switch
            - EPC connects to core switch (bridging wired/wireless)
            - UEs connect to eNodeB
            - eNodeB connects to EPC
            - Core switch managed by controller
            
            Requirements:
            - Instantiate all components
            - Bridge wired and wireless networks
            """
        )
    
    def example_9_testing_lab(self):
        """Example 9: Network Testing Lab"""
        return self._generate_and_save(
            "09_testing_lab",
            """
            Create a network testing laboratory:
            
            Components:
            - 1 test switch: test_sw
            - 1 controller: c1 at 192.168.1.100
            
            Test Hosts (different purposes):
            - client1: 10.0.0.10/24 (test client)
            - client2: 10.0.0.11/24 (test client)
            - server1: 10.0.0.100/24 (test server)
            - server2: 10.0.0.101/24 (test server)
            - monitor: 10.0.0.200/24 (monitoring host)
            
            Topology:
            - All hosts connect to test switch
            - Switch managed by controller
            
            Requirements:
            - Instantiate all nodes
            - Setup for performance testing
            """
        )
    
    def example_10_multi_controller(self):
        """Example 10: Multi-Controller SDN Network"""
        return self._generate_and_save(
            "10_multi_controller_sdn",
            """
            Create an SDN network with multiple controllers:
            
            Controllers:
            - c1: OpenDaylight at 192.168.1.100 (primary)
            - c2: ONOS at 192.168.1.101 (secondary)
            
            Switches:
            - 3 switches: s1, s2, s3
            
            Hosts:
            - 6 hosts: h1-h6
              * h1, h2 on s1 (10.0.1.1/24, 10.0.1.2/24)
              * h3, h4 on s2 (10.0.2.1/24, 10.0.2.2/24)
              * h5, h6 on s3 (10.0.3.1/24, 10.0.3.2/24)
            
            Topology:
            - Hosts connect to their designated switches
            - s1 managed by c1
            - s2 managed by c2
            - s3 managed by both (for demonstration)
            
            Requirements:
            - Instantiate all components
            - Demonstrate multi-controller scenario
            """
        )
    
    def run_all_examples(self):
        """Run all examples"""
        examples = [
            ("Basic SDN Network", self.example_1_basic_sdn),
            ("Simple 4G Wireless", self.example_2_simple_wireless),
            ("Redundant Network", self.example_3_redundant_network),
            ("Hierarchical Network", self.example_4_hierarchical_network),
            ("Datacenter Spine-Leaf", self.example_5_datacenter_spine_leaf),
            ("Campus Network", self.example_6_campus_network),
            ("IoT Edge Network", self.example_7_iot_network),
            ("Hybrid Wired+Wireless", self.example_8_hybrid_network),
            ("Testing Lab", self.example_9_testing_lab),
            ("Multi-Controller SDN", self.example_10_multi_controller)
        ]
        
        results = []
        
        for name, func in examples:
            try:
                filename = func()
                if filename:
                    results.append({"name": name, "status": "✓", "file": filename})
                else:
                    results.append({"name": name, "status": "✗", "file": None})
            except Exception as e:
                results.append({"name": name, "status": "✗", "error": str(e)})
        
        # Print summary
        print("\n" + "="*70)
        print("GENERATION SUMMARY")
        print("="*70)
        
        for r in results:
            status = r['status']
            name = r['name']
            if 'file' in r and r['file']:
                print(f"{status} {name}: {r['file']}")
            else:
                print(f"{status} {name}")
        
        successful = len([r for r in results if r['status'] == '✓'])
        print("\n" + "="*70)
        print(f"Successfully generated: {successful}/{len(examples)} examples")
        print(f"Output directory: {self.output_dir}/")
        print("="*70)
        
        return results


def main():
    """Main execution"""
    import sys
    
    # Create examples generator
    examples = LFTAIExamples(output_dir="ai_generated_examples")
    
    # Initialize generator (once for all examples)
    examples.init_generator(model="deepseek-r1")
    
    # Check if specific example requested
    if len(sys.argv) > 1:
        example_num = sys.argv[1]
        
        example_map = {
            "1": examples.example_1_basic_sdn,
            "2": examples.example_2_simple_wireless,
            "3": examples.example_3_redundant_network,
            "4": examples.example_4_hierarchical_network,
            "5": examples.example_5_datacenter_spine_leaf,
            "6": examples.example_6_campus_network,
            "7": examples.example_7_iot_network,
            "8": examples.example_8_hybrid_network,
            "9": examples.example_9_testing_lab,
            "10": examples.example_10_multi_controller
        }
        
        if example_num in example_map:
            example_map[example_num]()
        else:
            print(f"Unknown example: {example_num}")
            print("Available examples: 1-10, or 'all'")
    else:
        # Run all examples
        examples.run_all_examples()
    
    print("\nDone! Check the 'ai_generated_examples/' directory")
    print("   Run any example with: sudo python ai_generated_examples/[filename].py")


if __name__ == "__main__":
    main()
